[project]
name = "tabelas-esocial"
version = "0.1.0"
description = "Baixar tabelas do eSocial"
readme = "README.md"
requires-python = ">=3.15"
dependencies = [
    "psycopg>=3.3.2",
    "requests>=2.32.5",
]
